# Generated by Django 5.1.2 on 2024-10-20 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('64d4c6e4-7f8c-4a22-9859-3b88b8177841'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('content', models.CharField()),
                ('rating', models.IntegerField()),
                ('created_on', models.DateField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
