# Generated by Django 5.1.2 on 2024-10-20 06:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e40a0011-a3ef-40b5-bbf0-29a02184e946'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('genre', models.CharField(max_length=225)),
                ('release', models.DateField()),
            ],
        ),
    ]
